## Matcher les départements aux anciennes régions
il faut quand même changer à la main les accents des départements et régions

In [13]:
import pandas as pd

# Dictionnaire des régions et départements
regions_departments = {
    'Île-de-France': ['75', '77', '78', '91', '92', '93', '94', '95'],
    'Centre-Val de Loire': ['18', '28', '36', '37', '41', '45'],
    'Bourgogne-Franche-Comté': ['21', '25', '39', '58', '70', '71', '89', '90'],
    'Normandie': ['14', '27', '50', '61', '76'],
    'Hauts-de-France': ['02', '59', '60', '62', '80'],
    'Grand Est': ['08', '10', '51', '52', '54', '55', '57', '67', '68', '88'],
    'Pays de la Loire': ['44', '49', '53', '72', '85'],
    'Bretagne': ['22', '29', '35', '56'],
    'Nouvelle-Aquitaine': ['16', '17', '19', '23', '24', '33', '40', '47', '64', '79', '86', '87'],
    'Occitanie': ['09', '11', '12', '30', '31', '32', '34', '46', '48', '65', '66', '81', '82'],
    'Auvergne-Rhône-Alpes': ['01', '03', '07', '15', '26', '38', '42', '43', '63', '69', '73', '74'],
    'Provence-Alpes-Côte d’Azur': ['04', '05', '06', '13', '83', '84'],
    'Corse': ['02A', '02B'],
    'Guadeloupe': ['971'],
    'Martinique': ['972'],
    'Guyane': ['973'],
    'La Réunion': ['974'],
    'Mayotte': ['976']
}

# Fonction pour obtenir la région d'un département
def get_region(department):
    for region, departments in regions_departments.items():
        if department in departments:
            return region
    return 'Unknown'

# Lire le fichier CSV
file_path = 'departement.csv'
df = pd.read_csv(file_path)

# Extraire le numéro du département sans les zéros initiaux et gérer les cas alphanumériques
# Extraire le numéro du département et le formater à deux chiffres ou garder les codes alphanumériques tels quels
def extract_dept_number(dept):
    num = dept.split(' - ')[0]
    if num in ['2A', '2B']:
        return num  # Retourne les numéros alphanumériques tels quels ('2A', '2B')
    try:
        return str(int(num)).zfill(2)  # Convertit les numéros comme '001' en '01', '002' en '02'
    except ValueError:
        return num  # Retourne les autres cas tels quels


df['Numéro'] = df['Departement'].apply(extract_dept_number)

# Ajouter la colonne 'Région'
df['Région'] = df['Numéro'].apply(get_region)

# Sauvegarder le fichier modifié
output_path = 'departement_avec_regions.csv'
df.to_csv(output_path, index=False, encoding='utf-8')

# Afficher le dataframe modifié
df.head()

                     Departement Numéro                      Région
0                      001 - Ain     01        Auvergne-Rhône-Alpes
1                    002 - Aisne     02             Hauts-de-France
2                   003 - Allier     03        Auvergne-Rhône-Alpes
3  004 - Alpes-de-Haute-Provence     04  Provence-Alpes-Côte d’Azur
4             005 - Hautes-Alpes     05  Provence-Alpes-Côte d’Azur

## Mettre les nouvelles régions dans le fichier rendement

In [24]:
import pandas as pd

# Charger les fichiers CSV avec le séparateur correct
test_8_path = 'Test_8.csv'
departement_avec_regions_path = 'departement_avec_regions.csv'

# Lire les fichiers CSV avec le bon séparateur
test_8_df = pd.read_csv(test_8_path, sep=';', encoding='utf-8')
departement_avec_regions_df = pd.read_csv(departement_avec_regions_path, sep=';', encoding='utf-8')

# Vérifier les noms des colonnes
print(departement_avec_regions_df.columns)

# Fusionner les dataframes sur la colonne 'LIB_DEP' de test_8_df et 'Departement' de departement_avec_regions_df
result_df = pd.merge(test_8_df, departement_avec_regions_df[['Departement', 'Region']], left_on='LIB_DEP', right_on='Departement', how='left')

# Sauvegarder le fichier résultant
output_path = 'test_8_avec_regions.csv'
result_df.to_csv(output_path, index=False, encoding='utf-8')

# Afficher les premières lignes du dataframe modifié
result_df.head()

Index(['Departement', 'Numero', 'Region'], dtype='object')

,LIB_REG2,LIB_DEP,LIB_CODE,New_catetogorie,SURF_2010,SURF_2011,SURF_2012,SURF_2013,SURF_2014,SURF_2015,...,PROD_2016,PROD_2017,PROD_2018,PROD_2019,PROD_2020,PROD_2021,PROD_2022,PROD_2023,Departement,Region
0,11 - Île-de-France,077 - Seine-et-Marne,01 - Blé tendre d'hiver et épeautre,Blé,135 199,142 512,137 830,140 610,139 130,141 500,...,5 589 600,11 009 925,10 081 225,11 760 760,8 800 715,10 958 490,10 320 700,10 472 850,077 - Seine-et-Marne,Ile-de-France
1,11 - Île-de-France,077 - Seine-et-Marne,03 - Total blé tendre (01 + 02),Blé,135 518,142 872,138 240,141 210,139 620,141 795,...,5 599 800,11 043 135,10 108 175,11 814 000,8 901 585,11 019 495,10 401 450,10 514 841,077 - Seine-et-Marne,Ile-de-France
2,11 - Île-de-France,077 - Seine-et-Marne,06 - Total blé dur (04 + 05),Blé,1 981,1 471,1 590,1 115,730,675,...,18 800,55 250,42 840,28 800,49 350,65 920,68 340,52 313,077 - Seine-et-Marne,Ile-de-France
3,11 - Île-de-France,077 - Seine-et-Marne,10 - Total orge et escourgeon (08 + 09),Orge,40 473,42 389,43 680,42 325,45 900,47 590,...,2 646 320,3 912 250,3 752 460,4 971 470,3 566 115,3 902 290,3 869 845,4 213 297,077 - Seine-et-Marne,Ile-de-France
4,11 - Île-de-France,077 - Seine-et-Marne,13 - Total avoine (11 + 12),Cérélaes(autres),1 637,1 163,1 400,1 765,1 840,1 710,...,80 000,150 300,124 800,98 580,99 750,112 860,77 585,68 288,077 - Seine-et-Marne,Ile-de-France

In [6]:
import pandas as pd

# Nouveau dictionnaire de régions et départements
regions_departments = {
    'vendee': ['85'],
    'alsace': ['67', '68'],
    'ardeche': ['07'],
    'auvergne': ['03', '15', '43', '63'],
    'bourgogne': ['21', '58', '71', '89'],
    'bretagne': ['22', '29', '35', '56'],
    'camargue': ['13', '30'],
    'centre': ['18', '28', '36', '37', '41', '45'],
    'charentes': ['16', '17'],
    'corse': ['2A', '2B'],
    'provence-alpes-c-te-d-azur': ['04', '05', '06', '13', '83', '84'],
    'drome': ['26'],
    'franche-comte': ['25', '39', '70', '90'],
    'aquitaine': ['24', '33', '40', '47', '64'],
    'ile-de-re': ['17'],
    'jura': ['39'],
    'landes': ['40'],
    'limousin': ['19', '23', '87'],
    'lorraine': ['54', '55', '57', '88'],
    'lot': ['46'],
    'cevennes-lozere': ['48'],
    'lyonnais': ['69'],
    'midi-toulousain': ['31', '32', '82'],
    'normandie': ['14', '27', '50', '61', '76'],
    'pays-basque': ['64'],
    'pays-de-la-loire': ['44', '49', '53', '72', '85'],
    'perigord-dordogne': ['24'],
    'picardie': ['02', '60', '80'],
    'midi-pyrenees': ['09', '12', '31', '32', '46', '65', '81', '82'],
    'ile-de-france': ['75', '77', '78', '91', '92', '93', '94', '95']
}

# Fonction pour obtenir la région d'un département
def get_region(department):
    for region, departments in regions_departments.items():
        if department in departments:
            return region
    return 'Unknown'

# Lire le fichier CSV
file_path = 'Fichier_sources_rendement.csv'

# Essayer de lire le fichier avec des options pour gérer les erreurs de formatage
try:
    df = pd.read_csv(file_path, sep=None, engine='python', on_bad_lines='skip')
except Exception as e:
    print(f"Erreur lors de la lecture du fichier : {e}")
    raise

# Afficher les premières lignes pour vérifier les colonnes disponibles
print("Colonnes disponibles :")
print(df.columns)

# Supposons que la colonne contenant les départements s'appelle 'LIB_DEP'
department_column = 'LIB_DEP'

# Extraire le numéro du département et le formater correctement
def extract_dept_number(dept):
    num = dept.split(' - ')[0]
    if num in ['2A', '2B']:
        return num  # Retourne les numéros alphanumériques tels quels ('2A', '2B')
    try:
        return str(int(num)).zfill(2)  # Convertit les numéros comme '001' en '01', '002' en '02'
    except ValueError:
        return num  # Retourne les autres cas tels quels

# Ajouter la colonne 'Numéro' au DataFrame
df['Numéro'] = df[department_column].apply(extract_dept_number)

# Ajouter la colonne 'new_region'
df['new_region'] = df['Numéro'].apply(get_region)

# Sauvegarder le fichier modifié
output_path = 'Fichier_sources_rendement_avec_regions.csv'
df.to_csv(output_path, index=False, encoding='utf-8')

# Afficher les premières lignes du dataframe modifié
print(df.head())

Colonnes disponibles :
Index(['﻿LIB_REG2', 'LIB_DEP', 'LIB_CODE', 'New_catetogorie', 'Region',
       'SURF_2010', 'SURF_2011', 'SURF_2012', 'SURF_2013', 'SURF_2014',
       'SURF_2015', 'SURF_2016', 'SURF_2017', 'SURF_2018', 'SURF_2019',
       'SURF_2020', 'SURF_2021', 'SURF_2022', 'SURF_2023', 'REND_2010',
       'REND_2011', 'REND_2012', 'REND_2013', 'REND_2014', 'REND_2015',
       'REND_2016', 'REND_2017', 'REND_2018', 'REND_2019', 'REND_2020',
       'REND_2021', 'REND_2022', 'REND_2023', 'PROD_2010', 'PROD_2011',
       'PROD_2012', 'PROD_2013', 'PROD_2014', 'PROD_2015', 'PROD_2016',
       'PROD_2017', 'PROD_2018', 'PROD_2019', 'PROD_2020', 'PROD_2021',
       'PROD_2022', 'PROD_2023'],
      dtype='object')
            ﻿LIB_REG2               LIB_DEP  \
0  11 - Île-de-France  077 - Seine-et-Marne
1  11 - Île-de-France  077 - Seine-et-Marne
2  11 - Île-de-France  077 - Seine-et-Marne
3  11 - Île-de-France  077 - Seine-et-Marne
4  11 - Île-de-France  077 - Seine-et-Marne

                                  LIB_CODE   New_catetogorie         Region  \
0      01 - Blé tendre d'hiver et épeautre               Blé  Ile-de-France
1          03 - Total blé tendre (01 + 02)               Blé  Ile-de-France
2             06 - Total blé dur (04 + 05)               Blé  Ile-de-France
3  10 - Total orge et escourgeon (08 + 09)              Orge  Ile-de-France
4              13 - Total avoine (11 + 12)  Cérélaes(autres)  Ile-de-France

  SURF_2010 SURF_2011 SURF_2012 SURF_2013 SURF_2014  ...  PROD_2016  \
0   135 199   142 512   137 830   140 610   139 130  ...  5 589 600
1   135 518   142 872   138 240   141 210   139 620  ...  5 599 800
2     1 981     1 471     1 590     1 115       730  ...     18 800
3    40 473    42 389    43 680    42 325    45 900  ...  2 646 320
4     1 637     1 163     1 400     1 765     1 840  ...     80 000

    PROD_2017   PROD_2018   PROD_2019  PROD_2020   PROD_2021   PROD_2022  \
0  11 009 925  10 081 225  11 760 760  8 800 715  10 958 490  10 320 700
1  11 043 135  10 108 175  11 814 000  8 901 585  11 019 495  10 401 450
2      55 250      42 840      28 800     49 350      65 920      68 340
3   3 912 250   3 752 460   4 971 470  3 566 115   3 902 290   3 869 845
4     150 300     124 800      98 580     99 750     112 860      77 585

    PROD_2023 Numéro     new_region
0  10 472 850     77  ile-de-france
1  10 514 841     77  ile-de-france
2      52 313     77  ile-de-france
3   4 213 297     77  ile-de-france
4      68 288     77  ile-de-france

[5 rows x 49 columns]

In [7]:
import pandas as pd

# Nouveau dictionnaire de régions et départements
regions_departments = {
    'vendee': ['85'],
    'alsace': ['67', '68'],
    'ardeche': ['07'],
    'auvergne': ['03', '15', '43', '63'],
    'bourgogne': ['21', '58', '71', '89'],
    'bretagne': ['22', '29', '35', '56'],
    'camargue': ['13', '30'],
    'centre': ['18', '28', '36', '37', '41', '45'],
    'charentes': ['16', '17'],
    'corse': ['2A', '2B'],
    'provence-alpes-c-te-d-azur': ['04', '05', '06', '13', '83', '84'],
    'drome': ['26'],
    'franche-comte': ['25', '39', '70', '90'],
    'aquitaine': ['24', '33', '40', '47', '64'],
    'ile-de-re': ['17'],
    'jura': ['39'],
    'landes': ['40'],
    'limousin': ['19', '23', '87'],
    'lorraine': ['54', '55', '57', '88'],
    'lot': ['46'],
    'cevennes-lozere': ['48'],
    'lyonnais': ['69'],
    'midi-toulousain': ['31', '32', '82'],
    'normandie': ['14', '27', '50', '61', '76'],
    'pays-basque': ['64'],
    'pays-de-la-loire': ['44', '49', '53', '72', '85'],
    'perigord-dordogne': ['24'],
    'picardie': ['02', '60', '80'],
    'midi-pyrenees': ['09', '12', '31', '32', '46', '65', '81', '82'],
    'ile-de-france': ['75', '77', '78', '91', '92', '93', '94', '95']
}

# Fonction pour obtenir la région d'un département
def get_region(department):
    for region, departments in regions_departments.items():
        if department in departments:
            return region
    return 'Unknown'

# Lire le fichier CSV
file_path = 'Fichier_sources_rendement.csv'
df = pd.read_csv(file_path, sep=None, engine='python', error_bad_lines=False)

# Extraire le numéro du département sans les zéros initiaux et gérer les cas alphanumériques
def extract_dept_number(dept):
    num = dept.split(' - ')[0]
    if num in ['2A', '2B']:
        return num  # Retourne les numéros alphanumériques tels quels ('2A', '2B')
    try:
        return str(int(num)).zfill(2)  # Convertit les numéros comme '001' en '01', '002' en '02'
    except ValueError:
        return num  # Retourne les autres cas tels quels

# Ajouter la colonne 'Numéro' au DataFrame
df['Numéro'] = df['LIB_DEP'].apply(extract_dept_number)

# Ajouter la colonne 'new_region'
df['new_region'] = df['Numéro'].apply(get_region)

# Sauvegarder le fichier modifié
output_path = 'Fichier_sources_rendement_avec_regions_2.csv'
df.to_csv(output_path, index=False, encoding='utf-8')

# Afficher les premières lignes du dataframe modifié
print(df.head())

/tmp/ipykernel_4504/3791376002.py:46: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df = pd.read_csv(file_path, sep=None, engine='python', error_bad_lines=False)

            ﻿LIB_REG2               LIB_DEP  \
0  11 - Île-de-France  077 - Seine-et-Marne
1  11 - Île-de-France  077 - Seine-et-Marne
2  11 - Île-de-France  077 - Seine-et-Marne
3  11 - Île-de-France  077 - Seine-et-Marne
4  11 - Île-de-France  077 - Seine-et-Marne

                                  LIB_CODE   New_catetogorie         Region  \
0      01 - Blé tendre d'hiver et épeautre               Blé  Ile-de-France
1          03 - Total blé tendre (01 + 02)               Blé  Ile-de-France
2             06 - Total blé dur (04 + 05)               Blé  Ile-de-France
3  10 - Total orge et escourgeon (08 + 09)              Orge  Ile-de-France
4              13 - Total avoine (11 + 12)  Cérélaes(autres)  Ile-de-France

  SURF_2010 SURF_2011 SURF_2012 SURF_2013 SURF_2014  ...  PROD_2016  \
0   135 199   142 512   137 830   140 610   139 130  ...  5 589 600
1   135 518   142 872   138 240   141 210   139 620  ...  5 599 800
2     1 981     1 471     1 590     1 115       730  ...     18 800
3    40 473    42 389    43 680    42 325    45 900  ...  2 646 320
4     1 637     1 163     1 400     1 765     1 840  ...     80 000

    PROD_2017   PROD_2018   PROD_2019  PROD_2020   PROD_2021   PROD_2022  \
0  11 009 925  10 081 225  11 760 760  8 800 715  10 958 490  10 320 700
1  11 043 135  10 108 175  11 814 000  8 901 585  11 019 495  10 401 450
2      55 250      42 840      28 800     49 350      65 920      68 340
3   3 912 250   3 752 460   4 971 470  3 566 115   3 902 290   3 869 845
4     150 300     124 800      98 580     99 750     112 860      77 585

    PROD_2023 Numéro     new_region
0  10 472 850     77  ile-de-france
1  10 514 841     77  ile-de-france
2      52 313     77  ile-de-france
3   4 213 297     77  ile-de-france
4      68 288     77  ile-de-france

[5 rows x 49 columns]

In [8]:
import pandas as pd

# Nouveau dictionnaire de régions et départements
regions_departments = {
    'vendee': ['85'],
    'alsace': ['67', '68'],
    'ardeche': ['07'],
    'auvergne': ['03', '15', '43', '63'],
    'bourgogne': ['21', '58', '71', '89'],
    'bretagne': ['22', '29', '35', '56'],
    'camargue': ['13', '30'],
    'centre': ['18', '28', '36', '37', '41', '45'],
    'charentes': ['16', '17'],
    'corse': ['2A', '2B'],
    'provence-alpes-c-te-d-azur': ['04', '05', '06', '13', '83', '84'],
    'drome': ['26'],
    'franche-comte': ['25', '39', '70', '90'],
    'aquitaine': ['24', '33', '40', '47', '64'],
    'ile-de-re': ['17'],
    'jura': ['39'],
    'landes': ['40'],
    'limousin': ['19', '23', '87'],
    'lorraine': ['54', '55', '57', '88'],
    'lot': ['46'],
    'cevennes-lozere': ['48'],
    'lyonnais': ['69'],
    'midi-toulousain': ['31', '32', '82'],
    'normandie': ['14', '27', '50', '61', '76'],
    'pays-basque': ['64'],
    'pays-de-la-loire': ['44', '49', '53', '72', '85'],
    'perigord-dordogne': ['24'],
    'picardie': ['02', '60', '80'],
    'midi-pyrenees': ['09', '12', '31', '32', '46', '65', '81', '82'],
    'ile-de-france': ['75', '77', '78', '91', '92', '93', '94', '95']
}

# Fonction pour obtenir la région d'un département
def get_region(department):
    for region, departments in regions_departments.items():
        if department in departments:
            return region
    return 'Unknown'

# Lire le fichier CSV
file_path = 'Fichier_sources_rendement.csv'
df = pd.read_csv(file_path, sep=None, engine='python', on_bad_lines='skip')

# Extraire le numéro du département sans les zéros initiaux et gérer les cas alphanumériques
def extract_dept_number(dept):
    num = dept.split(' - ')[0]
    if num in ['2A', '2B']:
        return num  # Retourne les numéros alphanumériques tels quels ('2A', '2B')
    try:
        return str(int(num)).zfill(2)  # Convertit les numéros comme '001' en '01', '002' en '02'
    except ValueError:
        return num  # Retourne les autres cas tels quels

# Ajouter la colonne 'Numéro' au DataFrame
df['Numéro'] = df['LIB_DEP'].apply(extract_dept_number)

# Ajouter la colonne 'new_region'
df['new_region'] = df['Numéro'].apply(get_region)

# Sauvegarder le fichier modifié
output_path = 'Fichier_sources_rendement_avec_regions.csv'
df.to_csv(output_path, index=False, encoding='utf-8')

# Afficher les premières lignes du dataframe modifié
print(df.head())

            ﻿LIB_REG2               LIB_DEP  \
0  11 - Île-de-France  077 - Seine-et-Marne
1  11 - Île-de-France  077 - Seine-et-Marne
2  11 - Île-de-France  077 - Seine-et-Marne
3  11 - Île-de-France  077 - Seine-et-Marne
4  11 - Île-de-France  077 - Seine-et-Marne

                                  LIB_CODE   New_catetogorie         Region  \
0      01 - Blé tendre d'hiver et épeautre               Blé  Ile-de-France
1          03 - Total blé tendre (01 + 02)               Blé  Ile-de-France
2             06 - Total blé dur (04 + 05)               Blé  Ile-de-France
3  10 - Total orge et escourgeon (08 + 09)              Orge  Ile-de-France
4              13 - Total avoine (11 + 12)  Cérélaes(autres)  Ile-de-France

  SURF_2010 SURF_2011 SURF_2012 SURF_2013 SURF_2014  ...  PROD_2016  \
0   135 199   142 512   137 830   140 610   139 130  ...  5 589 600
1   135 518   142 872   138 240   141 210   139 620  ...  5 599 800
2     1 981     1 471     1 590     1 115       730  ...     18 800
3    40 473    42 389    43 680    42 325    45 900  ...  2 646 320
4     1 637     1 163     1 400     1 765     1 840  ...     80 000

    PROD_2017   PROD_2018   PROD_2019  PROD_2020   PROD_2021   PROD_2022  \
0  11 009 925  10 081 225  11 760 760  8 800 715  10 958 490  10 320 700
1  11 043 135  10 108 175  11 814 000  8 901 585  11 019 495  10 401 450
2      55 250      42 840      28 800     49 350      65 920      68 340
3   3 912 250   3 752 460   4 971 470  3 566 115   3 902 290   3 869 845
4     150 300     124 800      98 580     99 750     112 860      77 585

    PROD_2023 Numéro     new_region
0  10 472 850     77  ile-de-france
1  10 514 841     77  ile-de-france
2      52 313     77  ile-de-france
3   4 213 297     77  ile-de-france
4      68 288     77  ile-de-france

[5 rows x 49 columns]

In [9]:
import pandas as pd

# Nouveau dictionnaire des régions et départements
regions_departments = {
    'vendee': ['85'],
    'alsace': ['67', '68'],
    'ardeche': ['07'],
    'auvergne': ['03', '15', '43', '63'],
    'bourgogne': ['21', '58', '71', '89'],
    'bretagne': ['22', '29', '35', '56'],
    'camargue': ['13', '30'],
    'centre': ['18', '28', '36', '37', '41', '45'],
    'charentes': ['16', '17'],
    'corse': ['2A', '2B'],
    'provence-alpes-c-te-d-azur': ['04', '05', '06', '13', '83', '84'],
    'drome': ['26'],
    'franche-comte': ['25', '39', '70', '90'],
    'aquitaine': ['24', '33', '40', '47', '64'],
    'ile-de-re': ['17'],
    'jura': ['39'],
    'landes': ['40'],
    'limousin': ['19', '23', '87'],
    'lorraine': ['54', '55', '57', '88'],
    'lot': ['46'],
    'cevennes-lozere': ['48'],
    'lyonnais': ['69'],
    'midi-toulousain': ['31', '32', '82'],
    'normandie': ['14', '27', '50', '61', '76'],
    'pays-basque': ['64'],
    'pays-de-la-loire': ['44', '49', '53', '72', '85'],
    'perigord-dordogne': ['24'],
    'picardie': ['02', '60', '80'],
    'midi-pyrenees': ['09', '12', '31', '32', '46', '65', '81', '82'],
    'ile-de-france': ['75', '77', '78', '91', '92', '93', '94', '95'],
    'hauts-de-france': ['59', '62'],
    'grand-est': ['08', '10', '51', '52'],
    'poitou-charentes': ['79', '86'],
    'occitanie': ['11', '34', '66'],
    'auvergne-rhone-alpes': ['01', '38', '42', '73', '74'],
    'outre-mer': ['971', '972', '973', '974', '976']
}

# Fonction pour obtenir la région d'un département
def get_region(department):
    for region, departments in regions_departments.items():
        if department in departments:
            return region
    return 'Unknown'

# Lire le fichier CSV
file_path = 'Fichier_sources_rendement.csv'
df = pd.read_csv(file_path, sep=None, engine='python', error_bad_lines=False)

# Extraire le numéro du département sans les zéros initiaux et gérer les cas alphanumériques
def extract_dept_number(dept):
    num = dept.split(' - ')[0]
    if num in ['2A', '2B']:
        return num  # Retourne les numéros alphanumériques tels quels ('2A', '2B')
    try:
        return str(int(num)).zfill(2)  # Convertit les numéros comme '001' en '01', '002' en '02'
    except ValueError:
        return num  # Retourne les autres cas tels quels

# Ajouter la colonne 'Numéro'
df['Numéro'] = df['LIB_DEP'].apply(extract_dept_number)

# Ajouter la colonne 'new_region'
df['new_region'] = df['Numéro'].apply(get_region)

# Sauvegarder le fichier modifié
output_path = 'Fichier_sources_rendement_avec_regions_3.csv'
df.to_csv(output_path, index=False, encoding='utf-8')

# Afficher les premières lignes du dataframe modifié
df.head()

/tmp/ipykernel_4504/761862986.py:52: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df = pd.read_csv(file_path, sep=None, engine='python', error_bad_lines=False)

,﻿LIB_REG2,LIB_DEP,LIB_CODE,New_catetogorie,Region,SURF_2010,SURF_2011,SURF_2012,SURF_2013,SURF_2014,...,PROD_2016,PROD_2017,PROD_2018,PROD_2019,PROD_2020,PROD_2021,PROD_2022,PROD_2023,Numéro,new_region
0,11 - Île-de-France,077 - Seine-et-Marne,01 - Blé tendre d'hiver et épeautre,Blé,Ile-de-France,135 199,142 512,137 830,140 610,139 130,...,5 589 600,11 009 925,10 081 225,11 760 760,8 800 715,10 958 490,10 320 700,10 472 850,77,ile-de-france
1,11 - Île-de-France,077 - Seine-et-Marne,03 - Total blé tendre (01 + 02),Blé,Ile-de-France,135 518,142 872,138 240,141 210,139 620,...,5 599 800,11 043 135,10 108 175,11 814 000,8 901 585,11 019 495,10 401 450,10 514 841,77,ile-de-france
2,11 - Île-de-France,077 - Seine-et-Marne,06 - Total blé dur (04 + 05),Blé,Ile-de-France,1 981,1 471,1 590,1 115,730,...,18 800,55 250,42 840,28 800,49 350,65 920,68 340,52 313,77,ile-de-france
3,11 - Île-de-France,077 - Seine-et-Marne,10 - Total orge et escourgeon (08 + 09),Orge,Ile-de-France,40 473,42 389,43 680,42 325,45 900,...,2 646 320,3 912 250,3 752 460,4 971 470,3 566 115,3 902 290,3 869 845,4 213 297,77,ile-de-france
4,11 - Île-de-France,077 - Seine-et-Marne,13 - Total avoine (11 + 12),Cérélaes(autres),Ile-de-France,1 637,1 163,1 400,1 765,1 840,...,80 000,150 300,124 800,98 580,99 750,112 860,77 585,68 288,77,ile-de-france

In [10]:
import pandas as pd

# Nouveau dictionnaire des régions et départements
regions_departments = {
    'vendee': ['85'],
    'alsace': ['67', '68'],
    'ardeche': ['07'],
    'auvergne': ['03', '15', '43', '63'],
    'bourgogne': ['21', '58', '71', '89'],
    'bretagne': ['22', '29', '35', '56'],
    'camargue': ['13', '30'],
    'centre': ['18', '28', '36', '37', '41', '45'],
    'charentes': ['16', '17'],
    'corse': ['2A', '2B'],
    'provence-alpes-c-te-d-azur': ['04', '05', '06', '13', '83', '84'],
    'drome': ['26'],
    'franche-comte': ['25', '39', '70', '90'],
    'aquitaine': ['24', '33', '40', '47', '64'],
    'ile-de-re': ['17'],
    'jura': ['39'],
    'landes': ['40'],
    'limousin': ['19', '23', '87'],
    'lorraine': ['54', '55', '57', '88'],
    'lot': ['46'],
    'cevennes-lozere': ['48'],
    'lyonnais': ['69'],
    'midi-toulousain': ['31', '32', '82'],
    'normandie': ['14', '27', '50', '61', '76'],
    'pays-basque': ['64'],
    'pays-de-la-loire': ['44', '49', '53', '72', '85'],
    'perigord-dordogne': ['24'],
    'picardie': ['02', '60', '80'],
    'midi-pyrenees': ['09', '12', '31', '32', '46', '65', '81', '82'],
    'ile-de-france': ['75', '77', '78', '91', '92', '93', '94', '95'],
    'hauts-de-france': ['59', '62'],
    'grand-est': ['08', '10', '51', '52'],
    'poitou-charentes': ['79', '86'],
    'occitanie': ['11', '34', '66'],
    'auvergne-rhone-alpes': ['01', '38', '42', '73', '74'],
    'outre-mer': ['971', '972', '973', '974', '976']
}

# Fonction pour obtenir la région d'un département
def get_region(department):
    for region, departments in regions_departments.items():
        if department in departments:
            return region
    return 'Unknown'

# Lire le fichier CSV
file_path = 'Fichier_sources_rendement.csv'
df = pd.read_csv(file_path, sep=None, engine='python', on_bad_lines='skip')

# Extraire le numéro du département sans les zéros initiaux et gérer les cas alphanumériques
def extract_dept_number(dept):
    num = dept.split(' - ')[0]
    if num in ['2A', '2B']:
        return num  # Retourne les numéros alphanumériques tels quels ('2A', '2B')
    try:
        return str(int(num)).zfill(2)  # Convertit les numéros comme '001' en '01', '002' en '02'
    except ValueError:
        return num  # Retourne les autres cas tels quels

# Ajouter la colonne 'Numéro'
df['Numéro'] = df['LIB_DEP'].apply(extract_dept_number)

# Ajouter la colonne 'new_region'
df['new_region'] = df['Numéro'].apply(get_region)

# Sauvegarder le fichier modifié
output_path = 'Fichier_sources_rendement_avec_regions_4.csv'
df.to_csv(output_path, index=False, encoding='utf-8')

# Afficher les premières lignes du dataframe modifié
df.head()

,﻿LIB_REG2,LIB_DEP,LIB_CODE,New_catetogorie,Region,SURF_2010,SURF_2011,SURF_2012,SURF_2013,SURF_2014,...,PROD_2016,PROD_2017,PROD_2018,PROD_2019,PROD_2020,PROD_2021,PROD_2022,PROD_2023,Numéro,new_region
0,11 - Île-de-France,077 - Seine-et-Marne,01 - Blé tendre d'hiver et épeautre,Blé,Ile-de-France,135 199,142 512,137 830,140 610,139 130,...,5 589 600,11 009 925,10 081 225,11 760 760,8 800 715,10 958 490,10 320 700,10 472 850,77,ile-de-france
1,11 - Île-de-France,077 - Seine-et-Marne,03 - Total blé tendre (01 + 02),Blé,Ile-de-France,135 518,142 872,138 240,141 210,139 620,...,5 599 800,11 043 135,10 108 175,11 814 000,8 901 585,11 019 495,10 401 450,10 514 841,77,ile-de-france
2,11 - Île-de-France,077 - Seine-et-Marne,06 - Total blé dur (04 + 05),Blé,Ile-de-France,1 981,1 471,1 590,1 115,730,...,18 800,55 250,42 840,28 800,49 350,65 920,68 340,52 313,77,ile-de-france
3,11 - Île-de-France,077 - Seine-et-Marne,10 - Total orge et escourgeon (08 + 09),Orge,Ile-de-France,40 473,42 389,43 680,42 325,45 900,...,2 646 320,3 912 250,3 752 460,4 971 470,3 566 115,3 902 290,3 869 845,4 213 297,77,ile-de-france
4,11 - Île-de-France,077 - Seine-et-Marne,13 - Total avoine (11 + 12),Cérélaes(autres),Ile-de-France,1 637,1 163,1 400,1 765,1 840,...,80 000,150 300,124 800,98 580,99 750,112 860,77 585,68 288,77,ile-de-france

In [13]:
import pandas as pd

# Lecture du fichier CSV
df = pd.read_csv('meteo_data (14).csv')

# Calcul des variables par région et par année
df_region_year = df.groupby(['region', 'year']).agg({
    'Température moyenne': 'mean',
    'Température maximale': 'max', 
    'Température minimale': 'min',
    'Vitesse du vent': 'mean',
    'Température du vent': 'mean', 
    'Précipitations moyennes par jour': 'sum',
    'Record de précipitations sur une journée': 'max',
    'Humidité': 'mean',
    'Visibilité': 'mean', 
    'Couverture nuageuse': 'mean'
})

# Calcul du nombre de jours où la température a dépassé la moyenne annuelle
df_temp_sup = df.groupby(['region', 'year', 'month']).agg({'Température moyenne': 'mean'})
df_temp_sup = df_temp_sup.reset_index()
df_temp_sup['moy_annuelle'] = df_temp_sup.groupby(['region', 'year'])['Température moyenne'].transform('mean')
df_temp_sup['jours_chaleur'] = (df_temp_sup['Température moyenne'] > df_temp_sup['moy_annuelle']).astype(int)
df_temp_sup = df_temp_sup.groupby(['region', 'year'])['jours_chaleur'].sum()

# Calcul du nombre de jours où la température a été en dessous de la moyenne annuelle 
df_temp_inf = df.groupby(['region', 'year', 'month']).agg({'Température moyenne': 'mean'})  
df_temp_inf = df_temp_inf.reset_index()
df_temp_inf['moy_annuelle'] = df_temp_inf.groupby(['region', 'year'])['Température moyenne'].transform('mean')
df_temp_inf['jours_froid'] = (df_temp_inf['Température moyenne'] < df_temp_inf['moy_annuelle']).astype(int)
df_temp_inf = df_temp_inf.groupby(['region', 'year'])['jours_froid'].sum()

# Calcul du nombre de jours où l'humidité a été en dessous de la moyenne annuelle
df_humidite = df.groupby(['region', 'year', 'month']).agg({'Humidité': 'mean'})
df_humidite = df_humidite.reset_index() 
df_humidite['moy_annuelle'] = df_humidite.groupby(['region', 'year'])['Humidité'].transform('mean')
df_humidite['jours_humidite_basse'] = (df_humidite['Humidité'] < df_humidite['moy_annuelle']).astype(int)
df_humidite = df_humidite.groupby(['region', 'year'])['jours_humidite_basse'].sum()

# Calcul du nombre de jours consécutifs de précipitations supérieures à la moyenne
df['precip_sup_moy'] = df.groupby(['region', 'year'])['Précipitations moyennes par jour'].transform(lambda x: x > x.mean())
df['jours_precip_consecutifs'] = df.groupby(['region', 'year'])['precip_sup_moy'].transform(lambda x: x * (x.groupby((x != x.shift()).cumsum()).cumcount() + 1))
df_precip = df.groupby(['region', 'year'])['jours_precip_consecutifs'].max()

# Fusion des dataframes
df_final = pd.concat([df_region_year, df_temp_sup, df_temp_inf, df_humidite, df_precip], axis=1)
df_final = df_final.reset_index()

# Renommage des colonnes
df_final.columns = ['region', 'year', 'temp_moyenne', 'temp_max', 'temp_min', 'vitesse_vent', 'temp_vent', 
                    'precip_sum', 'record_precip', 'humidite_moy', 'visibilite_moy', 'couv_nuageuse_moy',
                    'jours_chaleur', 'jours_froid', 'jours_humidite_basse', 'jours_precip_consecutifs']

print(df_final)

# Sauvegarder le fichier modifié
output_path = 'meteo_data_(14)_all.csv'
df_final.to_csv(output_path, index=False, encoding='utf-8')

                        region  year  temp_moyenne  temp_max  temp_min  \
0                       alsace  2010     10.166667        27        -4
1                       alsace  2011     12.166667        25        -1
2                    aquitaine  2010     13.916667        26         3
3                    aquitaine  2011     15.750000        27         4
4                      ardeche  2010     12.083333        30        -1
5                      ardeche  2011     14.250000        29         1
6                     auvergne  2010      9.583333        25        -2
7                     auvergne  2011     11.333333        24         0
8                    bourgogne  2010     10.583333        26        -2
9                    bourgogne  2011     12.000000        24         1
10                    bretagne  2010     12.083333        22         4
11                    bretagne  2011     13.416667        20         6
12                    camargue  2010     15.083333        30         4
13                    camargue  2011     16.916667        28         5
14                      centre  2010     11.333333        26        -1
15                      centre  2011     12.833333        23         2
16             cevennes-lozere  2010      9.083333        26        -3
17             cevennes-lozere  2011     11.000000        26        -2
18                   charentes  2010     13.166667        25         3
19                   charentes  2011     14.833333        24         5
20                       corse  2010     16.416667        28         7
21                       corse  2011     17.083333        27         7
22                       drome  2010     11.500000        30        -2
23                       drome  2011     13.583333        28         0
24               franche-comte  2010      9.666667        26        -3
25               franche-comte  2011     11.500000        23         0
26               ile-de-france  2010     11.083333        27        -2
27               ile-de-france  2011     12.666667        23         2
28                   ile-de-re  2010     13.083333        24         4
29                   ile-de-re  2011     14.916667        22         6
30                        jura  2010      9.083333        25        -4
31                        jura  2011     11.000000        23        -2
32                      landes  2010     14.166667        27         4
33                      landes  2011     15.750000        26         5
34                    limousin  2010     10.916667        26        -1
35                    limousin  2011     12.666667        25         1
36                    lorraine  2010      9.583333        26        -4
37                    lorraine  2011     11.333333        23         0
38                         lot  2010     12.333333        29         1
39                         lot  2011     14.500000        29         1
40                    lyonnais  2010     10.500000        27        -2
41                    lyonnais  2011     12.333333        25        -1
42               midi-pyrenees  2010      9.916667        26        -2
43               midi-pyrenees  2011     11.500000        25        -1
44             midi-toulousain  2010     12.916667        30         1
45             midi-toulousain  2011     14.750000        29         2
46                   normandie  2010     11.000000        22         2
47                   normandie  2011     12.500000        20         5
48                 pays-basque  2010     14.166667        26         5
49                 pays-basque  2011     15.583333        24         6
50            pays-de-la-loire  2010     12.000000        26         1
51            pays-de-la-loire  2011     13.666667        22         4
52           perigord-dordogne  2010     12.500000        28         1
53           perigord-dordogne  2011     14.333333        28         2
54                    picardie  2010     10.500000        25        -1
55                    picardie  2011     12.000000        22         2
56  provence-alpes-c-te-d-azur  2010     14.333333        29         3
57  provence-alpes-c-te-d-azur  2011     16.000000        28         5
58                      vendee  2010     12.750000        25         3
59                      vendee  2011     14.333333        22         5

    vitesse_vent  temp_vent  precip_sum  record_precip  humidite_moy  \
0      13.833333   4.583333          50             69     91.750000
1      12.250000   6.666667          40             45     89.416667
2      16.750000   8.750000          45             80     87.500000
3      14.833333  10.916667          36             45     89.583333
4      16.833333   6.000000          48            125     87.333333
5      13.833333   8.416667          38            126     86.250000
6      15.916667   3.750000          50             92     91.916667
7      14.083333   5.833333          43             59     91.916667
8      16.250000   5.083333          48             79     91.333333
9      14.250000   7.000000          45             80     93.000000
10     23.833333   7.500000          43             64     87.000000
11     23.166667   9.333333          37             62     89.250000
12     20.750000  10.250000          41            113     79.416667
13     19.416667  12.166667          37             88     79.416667
14     16.750000   5.166667          35             57     90.916667
15     16.000000   7.333333          38             79     93.333333
16     16.583333   2.833333          66            141     90.083333
17     15.333333   4.750000          45            126     88.666667
18     20.916667   8.000000          48             71     86.916667
19     19.750000  10.416667          40             50     88.083333
20     18.416667  13.000000          51             89     81.250000
21     16.916667  13.750000          35             92     78.333333
22     17.333333   5.166667          43             78     87.333333
23     14.166667   7.500000          43             94     87.083333
24     16.000000   4.166667          68             73     92.666667
25     13.333333   6.416667          53             75     91.916667
26     16.583333   5.166667          34             51     90.916667
27     15.833333   7.583333          37             55     92.833333
28     23.833333   8.750000          49             51     85.000000
29     22.750000  11.083333          44             34     86.166667
30     15.750000   3.416667          85             78     92.666667
31     12.833333   5.750000          81             91     91.666667
32     15.833333   9.416667          48             80     87.166667
33     14.333333  11.500000          51             97     87.750000
34     16.000000   4.916667          50             92     91.583333
35     14.750000   7.166667          43             56     92.250000
36     16.000000   4.083333          46             59     91.666667
37     15.250000   5.916667          41             59     92.083333
38     13.666667   6.583333          46             54     90.750000
39     13.250000   8.333333          36             53     90.666667
40     15.750000   4.750000          59             86     91.916667
41     12.583333   6.916667          59             88     91.750000
42     14.333333   3.583333          53            117     87.250000
43     12.750000   6.083333          53             76     85.166667
44     14.750000   6.916667          47             84     90.083333
45     14.666667   8.583333          37             80     90.166667
46     22.916667   6.166667          40             53     88.333333
47     22.750000   7.916667          37             52     90.500000
48     18.416667   9.833333          51             60     85.083333
49     16.666667  12.166667          53            102     83.583333
50     19.666667   6.333333          38             52     89.916667
51     18.333333   8.416667          34             50     92.333333
52     14.083333   6.666667          47             56     90.916667
53     13.333333   8.583333          37             53     91.166667
54     18.666667   4.833333          44             75     90.916667
55     18.333333   6.916667          38             51     92.583333
56     19.833333   9.666667          46            155     80.333333
57     17.833333  11.500000          43            188     79.666667
58     22.083333   7.583333          44             52     87.500000
59     20.416667   9.833333          37             50     88.833333

    visibilite_moy  couv_nuageuse_moy  jours_chaleur  jours_froid  \
0         8.083333          48.083333              6            6
1         8.833333          35.250000              6            6
2         9.500000          37.500000              7            5
3         9.083333          37.250000              7            5
4         8.750000          36.750000              6            6
5         9.250000          26.333333              6            6
6         7.916667          49.833333              7            5
7         8.083333          44.083333              7            5
8         8.416667          47.833333              7            5
9         8.416667          43.500000              6            5
10        9.500000          43.916667              6            6
11        9.666667          45.916667              7            5
12        9.750000          27.583333              5            7
13       10.000000          22.916667              7            5
14        8.833333          47.833333              7            5
15        8.833333          44.833333              7            5
16        7.916667          50.083333              6            6
17        8.416667          44.333333              6            5
18        9.666667          37.833333              6            6
19        9.416667          37.333333              7            5
20        9.916667          29.583333              6            6
21       10.000000          20.750000              6            6
22        8.666667          37.166667              6            6
23        9.083333          28.750000              7            5
24        8.083333          48.833333              7            5
25        8.500000          38.666667              6            6
26        8.666667          49.166667              7            5
27        8.833333          45.416667              7            5
28        9.833333          38.250000              6            6
29        9.833333          38.916667              8            4
30        7.916667          51.083333              6            6
31        8.166667          43.416667              6            5
32        9.166667          38.750000              6            6
33        9.333333          36.083333              7            5
34        8.250000          47.750000              7            5
35        7.750000          45.750000              7            5
36        8.083333          53.000000              7            5
37        8.500000          44.583333              6            6
38        8.416667          43.583333              6            6
39        8.166667          40.333333              7            5
40        8.166667          47.166667              6            6
41        8.416667          39.500000              6            6
42        8.583333          36.000000              7            5
43        9.000000          30.000000              7            5
44        8.833333          41.166667              7            5
45        8.833333          37.250000              7            5
46        9.166667          47.750000              6            6
47        9.333333          47.083333              7            5
48        9.416667          38.500000              6            6
49        9.916667          34.166667              7            5
50        9.250000          41.833333              6            5
51        9.000000          44.000000              7            5
52        8.583333          43.416667              7            5
53        8.083333          40.750000              7            5
54        8.833333          50.083333              7            5
55        8.833333          46.666667              7            5
56        9.666667          26.750000              6            6
57        9.916667          21.333333              6            5
58        9.583333          40.000000              6            6
59        9.416667          41.166667              7            5

    jours_humidite_basse  jours_precip_consecutifs
0                      4                         2
1                      3                         3
2                      6                         3
3                      5                         1
4                      6                         2
5                      5                         2
6                      4                         2
7                      4                         4
8                      6                         2
9                      3                         4
10                     7                         3
11                     7                         1
12                     5                         4
13                     6                         2
14                     5                         4
15                     5                         4
16                     6                         4
17                     5                         2
18                     5                         2
19                     8                         2
20                     6                         3
21                     6                         2
22                     6                         3
23                     5                         2
24                     5                         2
25                     4                         4
26                     5                         3
27                     2                         3
28                     6                         2
29                     8                         2
30                     6                         2
31                     4                         5
32                     7                         2
33                     6                         2
34                     6                         2
35                     5                         2
36                     6                         2
37                     4                         3
38                     4                         3
39                     5                         1
40                     4                         2
41                     5                         5
42                     6                         2
43                     8                         3
44                     7                         2
45                     7                         1
46                     6                         5
47                     4                         3
48                     6                         1
49                     5                         2
50                     5                         3
51                     6                         4
52                     5                         3
53                     4                         2
54                     5                         2
55                     3                         3
56                     6                         3
57                     7                         2
58                     6                         3
59                     6                         1